### ISSUE TITLE
need to cd into wgetworker before building

### ISSUE THREAD

**Issue by hugomeiland** [nerdalize/wgetworker#1]
Hi,

I was just following the procedure for building the wget workoer docker; 
docker me$ docker build -t wgetworker .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat <mypath>/Dockerfile: no such file or directory

I think a "$cd wgetworker" is needed to become foolproof....

**Comment by dhrp** [comment]
Ok, I'll add that! Thanks!
